//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEmpaqueRocedes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biohorario
    {
        public int id_bio { get; set; }
        public string bihorario { get; set; }
        public Nullable<double> rango1 { get; set; }
        public Nullable<double> rango2 { get; set; }
        public Nullable<double> horas { get; set; }
        public Nullable<double> hora_t { get; set; }
    }
}
