//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEmpaqueRocedes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biohorario
    {
        public int id_bio { get; set; }
        public string bihorario { get; set; }
        public Nullable<double> rango1 { get; set; }
        public Nullable<double> rango2 { get; set; }
        public Nullable<double> horas { get; set; }
        public Nullable<double> hora_t { get; set; }
    }
}
