//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEmpaqueRocedes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bundle
    {
        public int Id_Bundle { get; set; }
        public Nullable<int> Id_Order { get; set; }
        public Nullable<int> NSeq { get; set; }
        public Nullable<int> Bld { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public Nullable<int> Quantity { get; set; }
        public byte[] Controlconcurrencia { get; set; }
    
        public virtual POrder POrder { get; set; }
    }
}
