//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEmpaqueRocedes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bundle
    {
        public int Id_Bundle { get; set; }
        public Nullable<int> Id_Order { get; set; }
        public Nullable<int> NSeq { get; set; }
        public Nullable<int> Bld { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public Nullable<int> Quantity { get; set; }
        public byte[] Controlconcurrencia { get; set; }
    
        public virtual POrder POrder { get; set; }
    }
}
