//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEmpaqueRocedes.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AuditoriaEntities : DbContext
    {
        public AuditoriaEntities()
            : base("name=AuditoriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bundle> Bundle { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Linea> Linea { get; set; }
        public virtual DbSet<Planta> Planta { get; set; }
        public virtual DbSet<POrder> POrder { get; set; }
        public virtual DbSet<Style> Style { get; set; }
        public virtual DbSet<tblUserEnvio> tblUserEnvio { get; set; }
        public virtual DbSet<tbBultosCodigosBarra> tbBultosCodigosBarra { get; set; }
        public virtual DbSet<tbCodigosBarraScan> tbCodigosBarraScan { get; set; }
        public virtual DbSet<tbcodigosCajas> tbcodigosCajas { get; set; }
        public virtual DbSet<tbCorteSecuenciaCaja> tbCorteSecuenciaCaja { get; set; }
        public virtual DbSet<tbUserEmpaque> tbUserEmpaque { get; set; }
    
        public virtual ObjectResult<getcorteBox_Result> getcorteBox(string codigobox, string usuario, string clasificacion)
        {
            var codigoboxParameter = codigobox != null ?
                new ObjectParameter("codigobox", codigobox) :
                new ObjectParameter("codigobox", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var clasificacionParameter = clasificacion != null ?
                new ObjectParameter("clasificacion", clasificacion) :
                new ObjectParameter("clasificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getcorteBox_Result>("getcorteBox", codigoboxParameter, usuarioParameter, clasificacionParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> ExtraefechaServidor(Nullable<int> val)
        {
            var valParameter = val.HasValue ?
                new ObjectParameter("val", val) :
                new ObjectParameter("val", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("ExtraefechaServidor", valParameter);
        }
    
        public virtual ObjectResult<getInfobox_Result> getInfobox(string box)
        {
            var boxParameter = box != null ?
                new ObjectParameter("box", box) :
                new ObjectParameter("box", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getInfobox_Result>("getInfobox", boxParameter);
        }
    }
}
