//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEmpaqueRocedes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacion
    {
        public int id_operacion { get; set; }
        public string descripcion { get; set; }
        public string descripcion_completa { get; set; }
        public string codigo { get; set; }
        public Nullable<double> SAM { get; set; }
    }
}
