//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEmpaqueRocedes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacion
    {
        public int id_operacion { get; set; }
        public string descripcion { get; set; }
        public string descripcion_completa { get; set; }
        public string codigo { get; set; }
        public Nullable<double> SAM { get; set; }
    }
}
