//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEmpaqueRocedes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBultosCodigosBarra
    {
        public int id { get; set; }
        public Nullable<int> idCorte { get; set; }
        public int idBulto { get; set; }
        public string codigoBarra { get; set; }
        public string talla { get; set; }
        public Nullable<int> secuenciaUnidades { get; set; }
        public Nullable<System.DateTime> fechaGenerado { get; set; }
        public Nullable<System.DateTime> fechaEscaneado { get; set; }
        public Nullable<System.DateTime> fechaImpreso { get; set; }
        public Nullable<System.DateTime> fechaAnulado { get; set; }
        public string corteCompleto { get; set; }
        public string estado { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Restante { get; set; }
    }
}
