//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEmpaqueRocedes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBultosCodigosBarra
    {
        public int id { get; set; }
        public Nullable<int> idCorte { get; set; }
        public int idBulto { get; set; }
        public string codigoBarra { get; set; }
        public string talla { get; set; }
        public Nullable<int> secuenciaUnidades { get; set; }
        public Nullable<System.DateTime> fechaGenerado { get; set; }
        public Nullable<System.DateTime> fechaEscaneado { get; set; }
        public string estado { get; set; }
        public string corteCompleto { get; set; }
        public Nullable<System.DateTime> fechaImpreso { get; set; }
        public Nullable<System.DateTime> fechaAnulado { get; set; }
    }
}
