//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEmpaqueRocedes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCorteSecuenciaCaja
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public Nullable<int> idcorte { get; set; }
        public Nullable<int> sec { get; set; }
        public string corte { get; set; }
    }
}
