//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEmpaqueRocedes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCodigosBarraScan
    {
        public int id { get; set; }
        public string codigoBox { get; set; }
        public string codigoBarra { get; set; }
        public Nullable<System.DateTime> fechaEscaneado { get; set; }
        public Nullable<bool> estado { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechaAnulado { get; set; }
        public string usuarioAnulado { get; set; }
    
        public virtual tbcodigosCajas tbcodigosCajas { get; set; }
    }
}
