//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEmpaqueRocedes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcodigosCajas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbcodigosCajas()
        {
            this.tbCodigosBarraScan = new HashSet<tbCodigosBarraScan>();
        }
    
        public string codigoBox { get; set; }
        public Nullable<int> idCorte { get; set; }
        public string estilo { get; set; }
        public Nullable<int> secBoxXCorte { get; set; }
        public Nullable<System.DateTime> fechaGenerado { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> numeroImpresion { get; set; }
        public Nullable<System.DateTime> fechaImpresion { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechaAnulado { get; set; }
        public string usuarioAnulado { get; set; }
        public string corteCompleto { get; set; }
        public string clasificacion { get; set; }
        public string color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCodigosBarraScan> tbCodigosBarraScan { get; set; }
    }
}
