//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEmpaqueRocedes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcodigosCajas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbcodigosCajas()
        {
            this.tbCodigosBarraScan = new HashSet<tbCodigosBarraScan>();
        }
    
        public string codigoBox { get; set; }
        public Nullable<int> idCorte { get; set; }
        public string estilo { get; set; }
        public Nullable<int> secBoxXCorte { get; set; }
        public Nullable<System.DateTime> fechaGenerado { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> numeroImpresion { get; set; }
        public Nullable<System.DateTime> fechaImpresion { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechaAnulado { get; set; }
        public string usuarioAnulado { get; set; }
        public string corteCompleto { get; set; }
        public string clasificacion { get; set; }
        public string color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCodigosBarraScan> tbCodigosBarraScan { get; set; }
    }
}
