//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEmpaqueRocedes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserEnvio
    {
        public int idUserEnvio { get; set; }
        public string nameMemberShip { get; set; }
        public string nombreUsuario { get; set; }
        public string modulo { get; set; }
    }
}
