//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEmpaqueRocedes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPorderSinGuion
    {
        public int id { get; set; }
        public Nullable<int> idCorte { get; set; }
        public string corte { get; set; }
        public Nullable<int> idEstilo { get; set; }
        public string estilo { get; set; }
        public Nullable<int> unidades { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public string usuario { get; set; }
    }
}
